spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bulletinboard}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    show-sql: true

logging:
  level:
    com.bulletinboard: DEBUG
    org.springframework.web: DEBUG
